version: "3.8"

services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123456789 # Chỉnh sửa lại đúng tên biến
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dockervu
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dockervu

volumes:
  mysql-data:

networks:
  dockervu:
    driver: bridge
