server:
  port: 8080
  address: localhost
spring:
  application:
    name: BE_PBL6_FastOrderSystem
  main:
    allow-circular-references: true
  datasource:
    # username: root
    # password: 123456789
    # url: jdbc:mysql://localhost:3306/db_pbl6
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://127.0.0.1:3306/db_pbl6}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456789}
    security:
     jwt:
       signerKey: "W31fqJQUxdNSy/Y+F+RFsa/Zi4hx3sX2tfRH/dAk/0342mbKCFpdljSyUkeE59vxGYdSPYIAW2UW+pExDCD+1Q=="
       valid-duration: 86400 # 1 day
       refreshable-duration: 86400 # 1 day
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
