server:
  port: 8080
spring:
  application:
    name: BE_PBL6_FastOrderSystem
  main:
    allow-circular-references: true
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/db_pbl6
    driver-class-name: com.mysql.jdbc.Driver
    security:
      jwt:
        secret-key: xTKk7Ald/su3sDOWzUozdd8E/7X5q6HYKUKZfl+4qrQ=
        expire-length: 3600000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
logging:
  level:
    com:
      example:
        BE_PBL6_FastOrderSystem:
          service:
            Impl:
              ProductServiceImpl=DEBUG: INFO